export const columns = [
  {key:'model',       label:'Модель',         group:'core',        sortable:true},
  {key:'manufacturer',label:'Производитель',  group:'core',        sortable:true},
  {key:'segment',     label:'Сегмент',        group:'core',        sortable:true},
  {key:'type',        label:'Тип',            group:'core',        sortable:true},
  {key:'maxPixels',   label:'Макс. пикс.',    group:'performance', sortable:true, gk:'maxPixels', fmt:'mpx'},
  {key:'fps',         label:'FPS',            group:'performance', sortable:true, gk:'fps'},
  {key:'refreshRate', label:'Refresh Hz',     group:'performance', sortable:true, gk:'refreshRate'},
  {key:'hdr',         label:'HDR',            group:'performance', sortable:true, gk:'hdr',       fmt:'hdr'},
  {key:'tenBit',      label:'10-bit',         group:'performance', sortable:true,                 fmt:'bool'},
  {key:'latency',     label:'Latency',        group:'performance', sortable:true, gk:'latency',   fmt:'latency'},
  {key:'genlock',     label:'Genlock',        group:'performance', sortable:true, gk:'genlock',   fmt:'genlock'},
  {key:'ethernetPorts',label:'Ethernet порты',group:'interfaces',  sortable:true},
  {key:'fiber',       label:'Fiber',          group:'interfaces',                                 fmt:'bool'},
  {key:'hdmiIn',      label:'HDMI In',        group:'interfaces'},
  {key:'dpIn',        label:'DP In',          group:'interfaces'},
  {key:'wifi',        label:'Wi-Fi',          group:'interfaces',                                 fmt:'bool'},
  {key:'lte',         label:'4G/LTE',         group:'interfaces',                                 fmt:'bool'},
  {key:'scaling',     label:'Scaling',        group:'processing',                                 fmt:'bool'},
  {key:'pip',         label:'PIP/Layers',     group:'processing',  sortable:true, gk:'pip'},
  {key:'colorCal',    label:'Color Cal.',     group:'processing',                gk:'colorCal',  fmt:'bool'},
  {key:'lowBrightness',label:'Low Brt.',      group:'processing',                gk:'lowBrightness',fmt:'bool'},
  {key:'dithering',   label:'Dithering',      group:'processing',                gk:'dithering', fmt:'bool'},
  {key:'cloudPlatform',label:'Cloud',         group:'software',    sortable:true, gk:'cloudPlatform'},
  {key:'remoteControl',label:'Remote Ctrl',   group:'software',                                  fmt:'bool'},
  {key:'api',         label:'API/SDK',        group:'software',    gk:'api',                     fmt:'bool'},
  {key:'mobileApp',   label:'Mobile App',     group:'software',                                  fmt:'bool'},
  {key:'bestUse',     label:'Best Use Case',  group:'commercial'},
  {key:'setupComplexity',label:'Сложность',   group:'commercial',  sortable:true},
  {key:'reliability', label:'Надёжность',     group:'commercial',  sortable:true, fmt:'stars'},
  {key:'price',       label:'Цена (USD)',     group:'commercial',  sortable:true, gk:'price',    fmt:'price'},
  {key:'availability',label:'Наличие',        group:'commercial'},
  {key:'warranty',    label:'Гарантия (лет)', group:'commercial',  sortable:true},
];

export const presets = {
  broadcast: { segment:'Broadcast', hdr:true, genlock:true },
  xr:        { segment:'XR / Virtual', hdr:true, genlock:true },
  rental:    { manufacturer:'Colorlight', hdr:false },
  outdoor:   { segment:'', q:'Outdoor' },
  budget:    { segment:'Budget', hdr:false, cloud:false },
  pro:       { segment:'Professional', hdr:true },
};
